### ISSUE TITLE
Add "Monthly composite" as new option to composite_function

### ISSUE THREAD

**Issue by agronomofiorentini** [Permian-Global-Research/rsi#59]
Dear Contributors,
I want to thank you again for creating this package, which is easy to install and use.

I would like to ask you if it is possible to add "composite_function" the "montly composite", which can be useful to many users.
Or if you could tell us the mode using rstac to perform a monthly composite.

Below I leave a code that allows you to do some testing

```r
library(mapedit)
library(rsi)
library(sf)

# Create the Area of interest

AOI_Create<-editMap()

#AOI_Create<-AOI_Create$finished

# Change the crs from WGS84 to UTM system

centroid_coords <- st_coordinates(st_centroid(AOI_Create))

utm_zone <- floor((centroid_coords[1] + 180) / 6) + 1

aoi_utm <- st_transform(AOI_Create, paste0("+proj=utm +zone=", utm_zone))

aoi<-aoi_utm

asset_names<-rsi::sentinel2_band_mapping$planetary_computer_v1

# Costum query function

custom_query_function <- function(bbox, stac_source, collection, start_date, end_date, limit, ...) {

  geometry <- rstac::cql2_bbox_as_geojson(bbox)
  datetime <- rstac::cql2_interval(start_date, end_date)

  request <- rstac::ext_filter(
    rstac::stac(stac_source),
    collection == {{collection}} &&
      t_intersects(datetime, {{datetime}}) &&
      s_intersects(geometry, {{geometry}}) &&
      `eo:cloud_cover` < 30
  )

  rstac::items_fetch(rstac::post_request(request))

}

# Download

ciao <- get_sentinel2_imagery(aoi=aoi,
                              start_date = as.character("2023-09-01"),
                              end_date = as.character("2024-03-31"),
                              pixel_x_size = 10,
                              pixel_y_size = 10,
                              asset_names = sentinel2_band_mapping$planetary_computer_v1,
                              query_function = custom_query_function,
                              output_filename = "ciao.tif",
                              composite_function = "mean")
```

Thanks again,
Cheers

**Comment by mikemahoney218** [comment]
Hey @agronomofiorentini !

I'm a little bit cautious about building this into rsi itself, because people often want a very specific definition of their interval -- for instance, meaning "30 days" rather than "a named month" -- which means it's hard to build this into rsi in a way that suits every use case.

What we normally do instead is encourage people to use `vapply()`, or other apply functions, in order to define their intervals and call `get_stac_data()` multiple times. This should be just as fast as if we handled it inside the `get_stac_data()` function, but is a lot more flexible. There's an example on the website here:
https://permian-global-research.github.io/rsi/articles/How-can-I-.html#get-one-composite-per-year-month-or-other-interval

Hopefully it's clear how you could use `glue()` to build the output filename as well as the date range, and how this would work for months. Let me know if it isn't, or if I'm not understanding what you're looking for!
