### ISSUE TITLE
Retrieve not composite STAC - but a stack multi date layer?

### ISSUE THREAD

**Issue by agronomofiorentini** [Permian-Global-Research/rsi#6]
First of all I congratulate you, very useful and easy to use package.

I ask you a question, in your plans of development is there the possibility of being able to download not a composite of a month but individual images that are filtered for cloud cover.

Meaning that instead of getting a composite create a raster stack where there are individual dates (obviously for each band)

**Comment by mikemahoney218** [comment]
Howdy @agronomofiorentini ! Yes, this should be possible by setting `composite_function = NULL`:

``` r
library(rsi)
future::plan("multisession")

aoi <- sf::st_point(c(-74.912131, 44.080410)) |> 
  sf::st_sfc() |> 
  sf::st_set_crs(4326) |> 
  sf::st_transform(3857) |> 
  sf::st_buffer(1000)

images <- get_landsat_imagery(
  aoi = aoi,
  start_date = "2022-06-01",
  end_date = "2022-08-01",
  composite_function = NULL
)

images
#> [1] "island_dear_left_2022-07-27T15:44:51.989020Z.tif"
#> [2] "island_dear_left_2022-07-03T15:45:06.204955Z.tif"
#> [3] "island_dear_left_2022-06-17T15:45:03.055481Z.tif"
#> [4] "island_dear_left_2022-06-09T15:44:23.649712Z.tif"
#> [5] "island_dear_left_2022-06-01T15:44:51.569374Z.tif"
```

<sup>Created on 2023-11-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

You need the most recent version of rsi (from three weeks ago), because this was temporarily broken, but with the most recent version this will download individual images, appending the `datetime` of each item to the end if it exists or a sequential ID if it doesn't. I think the documentation needs to be more clear about this feature (and I don't _love_ the million different things `composite_function` controls right now) -- but this _should_ work for this use case :smile:

**Comment by agronomofiorentini** [comment]
sorry for the late reply.

It's working as you perfectly explained.

Can we filter by cloud cover? anyway great.

**Comment by mikemahoney218** [comment]
Just to update the second half of this issue: you can now pass CQL2 queries to `query_function` to filter based on cloud cover. Please open a new issue if this doesn't work or could be improved for your use-case :smile: 

https://permian-global-research.github.io/rsi/articles/Downloading-data-from-STAC-APIs-using-rsi.html#using-cql2-to-refine-queries-to-stac-apis
